# data/themes.py

themes = {
    "Stop Motion": {
        "descriptors": [
            "textured fragments",
            "layered ridges",
            "staggered frames",
            "mechanical contours",
            "embossed transitions",
            "intermittent movements",
            "pixelated planes",
            "static reliefs",
            "irregular grooves",
            "animated distortions",
            "carved textures",
            "distorted outlines",
            "sculptural undulations",
        ],
        "primary_elements": [
            "fragmented forms",
            "mechanical structures",
            "layered textures",
            "pixelated surfaces",
            "sculptural shapes",
            "animated elements",
        ],
        "modifiers": [
            "stop-start movements",
            "animated deformations",
            "carved surfaces",
            "distorted outlines",
            "sculptural undulations",
        ],
        "context": [
            "a dynamic workspace",
            "an industrial setting",
            "a fragmented environment",
            "a motion-laden backdrop",
        ],
        "mood": ["dynamic", "energetic", "whimsical"],
        "architectural_elements": ["mechanical structures", "steampunk gears"],
        "style": ["experimental animation", "abstract motion"],
    },
    "Minimal Line": {
        "descriptors": [
            "elegant contours",
            "continuous edges",
            "flat planes",
            "linear indentations",
            "subtle reliefs",
            "abstract lines",
            "thin grooves",
            "delicate ridges",
            "sparse layers",
            "refined engravings",
            "flowing silhouettes",
            "geometric curves",
            "clean undulations",
            "shallow facets",
        ],
        "primary_elements": [
            "simple contours",
            "continuous edges",
            "flat surfaces",
            "linear indentations",
            "abstract lines",
            "flowing shapes",
        ],
        "modifiers": [
            "minimal relief",
            "thin grooves",
            "delicate ridges",
            "sparse planes",
            "subtle engravings",
            "clean undulations",
        ],
        "context": [
            "a serene environment",
            "a minimalist space",
            "a clean backdrop",
            "an abstract setting",
        ],
    },
    "Laser": {
        "descriptors": [
            "precision edges",
            "intersecting planes",
            "angular cuts",
            "sharp grooves",
            "laser-etched ridges",
            "defined outlines",
            "fine trenches",
            "cutting surfaces",
            "abstract lattice",
            "geometric engravings",
            "smooth gradients",
            "cut-away sections",
            "reflective surfaces",
            "crisp folds",
        ],
        "primary_elements": [
            "sharp edges",
            "intersecting planes",
            "angular cuts",
            "precision grooves",
            "laser-etched ridges",
            "defined outlines",
        ],
        "modifiers": [
            "fine trenches",
            "cutting surfaces",
            "geometric engravings",
            "smooth gradients",
            "reflective surfaces",
            "crisp folds",
        ],
        "context": [
            "a high-tech environment",
            "a futuristic setting",
            "an industrial backdrop",
            "a laser-focused scene",
        ],
    },
    "Tokyo": {
        "descriptors": [
            "layered geometry",
            "urban ridges",
            "fragmented surfaces",
            "tessellated forms",
            "rising planes",
            "compressed contours",
            "abstract structures",
            "jagged outlines",
            "towering shapes",
            "angular intersections",
            "stacked layers",
            "repetitive patterns",
            "verticality",
            "chaotic ridges",
        ],
        "primary_elements": [
            "urban ridges",
            "layered geometry",
            "fragmented surfaces",
            "tessellated forms",
            "towering shapes",
            "angular intersections",
        ],
        "modifiers": [
            "compressed contours",
            "jagged outlines",
            "repetitive patterns",
            "verticality",
            "chaotic ridges",
            "stacked layers",
        ],
        "context": [
            "a bustling cityscape",
            "an urban jungle",
            "a metropolitan backdrop",
            "a towering skyline",
        ],
    },
    "Cubism": {
        "descriptors": [
            "fractured surfaces",
            "sharp contours",
            "overlapping planes",
            "fragmented ridges",
            "geometric reliefs",
            "angled shapes",
            "disjointed forms",
            "sharp intersections",
            "broken geometries",
            "layered facets",
            "structural distortions",
            "abstract breaks",
            "angular undulations",
        ],
        "primary_elements": [
            "fractured surfaces",
            "sharp contours",
            "overlapping planes",
            "fragmented ridges",
            "geometric reliefs",
            "angled shapes",
        ],
        "modifiers": [
            "disjointed forms",
            "sharp intersections",
            "broken geometries",
            "layered facets",
            "structural distortions",
            "abstract breaks",
        ],
        "context": [
            "an abstract gallery",
            "a fragmented environment",
            "a geometric setting",
            "a cubist-inspired backdrop",
        ],
    },
    "Illustration": {
        "descriptors": [
            "bold contours",
            "exaggerated ridges",
            "flowing lines",
            "engraved planes",
            "rounded forms",
            "playful distortions",
            "layered grooves",
            "detailed reliefs",
            "outlined shapes",
            "textured surfaces",
            "gentle undulations",
            "carved impressions",
        ],
        "primary_elements": [
            "bold contours",
            "exaggerated ridges",
            "flowing lines",
            "engraved planes",
            "rounded forms",
            "playful distortions",
        ],
        "modifiers": [
            "layered grooves",
            "detailed reliefs",
            "outlined shapes",
            "textured surfaces",
            "gentle undulations",
            "carved impressions",
        ],
        "context": [
            "a vibrant illustration",
            "a creative workspace",
            "an artistic backdrop",
            "a dynamic drawing environment",
        ],
    },
    "Surrealism": {
        "descriptors": [
            "fluid forms",
            "warped planes",
            "abstract ridges",
            "melting shapes",
            "disjointed contours",
            "flowing deformations",
            "undulating surfaces",
            "protruding facets",
            "dreamlike grooves",
            "engraved textures",
            "distorted geometry",
            "surreal reliefs",
            "elongated forms",
        ],
        "primary_elements": [
            "fluid forms",
            "warped planes",
            "abstract ridges",
            "melting shapes",
            "disjointed contours",
            "flowing deformations",
        ],
        "modifiers": [
            "undulating surfaces",
            "protruding facets",
            "dreamlike grooves",
            "engraved textures",
            "distorted geometry",
            "surreal reliefs",
        ],
        "context": [
            "a dreamscape",
            "a fantastical environment",
            "a surreal setting",
            "an abstract dream world",
        ],
    },
    "Art Rock": {
        "descriptors": [
            "jagged contours",
            "angular ridges",
            "broken planes",
            "fractured surfaces",
            "embossed textures",
            "sculptural forms",
            "sharp reliefs",
            "disjointed geometry",
            "irregular grooves",
            "abstract outlines",
            "expressive distortions",
            "chaotic layers",
            "edgy facets",
        ],
        "primary_elements": [
            "jagged contours",
            "angular ridges",
            "broken planes",
            "fractured surfaces",
            "embossed textures",
            "sculptural forms",
        ],
        "modifiers": [
            "sharp reliefs",
            "disjointed geometry",
            "irregular grooves",
            "abstract outlines",
            "expressive distortions",
            "chaotic layers",
        ],
        "context": [
            "a rock concert stage",
            "an edgy environment",
            "a dynamic backdrop",
            "a chaotic artistic setting",
        ],
    },
    "BW (Black & White)": {
        "descriptors": [
            "high contrasts",
            "defined edges",
            "monochromatic planes",
            "bold contours",
            "black ridges",
            "white grooves",
            "stark surfaces",
            "crisp outlines",
            "linear distortions",
            "contrasting reliefs",
            "abstract layers",
            "minimal facets",
            "sculptural depth",
        ],
        "primary_elements": [
            "sharp contrasts",
            "defined edges",
            "monochromatic planes",
            "bold contours",
            "black ridges",
            "white grooves",
        ],
        "modifiers": [
            "stark surfaces",
            "crisp outlines",
            "linear distortions",
            "contrasting reliefs",
            "abstract layers",
            "minimal facets",
        ],
        "context": [
            "a monochrome environment",
            "a stark setting",
            "a black and white backdrop",
            "a high-contrast scene",
        ],
    },
    "Neon Noir": {
        "descriptors": [
            "vibrant ridges",
            "sharp contours",
            "angular planes",
            "etched surfaces",
            "dark grooves",
            "geometric outlines",
            "neon facets",
            "contrasting reliefs",
            "fragmented surfaces",
            "reflective engravings",
            "urban distortions",
            "glowing ridges",
            "futuristic forms",
        ],
        "primary_elements": [
            "bold ridges",
            "sharp contours",
            "angular planes",
            "etched surfaces",
            "dark grooves",
            "geometric outlines",
        ],
        "modifiers": [
            "neon facets",
            "contrasting reliefs",
            "fragmented surfaces",
            "reflective engravings",
            "urban distortions",
            "glowing ridges",
        ],
        "context": [
            "a neon-lit cityscape",
            "a futuristic urban environment",
            "a dark, glowing backdrop",
            "a high-tech noir setting",
        ],
    },
    "Gradient": {
        "descriptors": [
            "seamless transitions",
            "layered contours",
            "soft ridges",
            "fluid planes",
            "subtle grooves",
            "gradient reliefs",
            "blended surfaces",
            "curved deformations",
            "flowing outlines",
            "abstract topography",
            "gentle undulations",
            "tonal layers",
            "smooth shapes",
        ],
        "primary_elements": [
            "smooth transitions",
            "layered contours",
            "soft ridges",
            "fluid planes",
            "subtle grooves",
            "gradient reliefs",
        ],
        "modifiers": [
            "blended surfaces",
            "curved deformations",
            "flowing outlines",
            "abstract topography",
            "gentle undulations",
            "tonal layers",
        ],
        "context": [
            "a harmonious environment",
            "a fluid backdrop",
            "a gradient-filled setting",
            "a seamless scene",
        ],
    },
    "Deep Dream": {
        "descriptors": [
            "chaotic ridges",
            "fluid deformations",
            "layered grooves",
            "surreal contours",
            "repeating forms",
            "deep fractals",
            "intricate surfaces",
            "warped planes",
            "abstract topography",
            "twisted outlines",
            "flowing reliefs",
            "complex undulations",
            "dreamlike geometry",
        ],
        "primary_elements": [
            "chaotic ridges",
            "fluid deformations",
            "layered grooves",
            "surreal contours",
            "repeating forms",
            "deep fractals",
        ],
        "modifiers": [
            "intricate surfaces",
            "warped planes",
            "abstract topography",
            "twisted outlines",
            "flowing reliefs",
            "complex undulations",
        ],
        "context": [
            "a deep dreamscape",
            "a fractal environment",
            "a surreal backdrop",
            "an abstract dream setting",
        ],
    },
}
